import Foundation

extension Strings {
    static let enAbout: [String: String] = [
        "about.title": "About this data",
        "about.build": "This build",
        "about.dataset": "Dataset",
        "about.lastUpdated": "Last updated",
        "about.seasonStart": "Season start",
        "about.districts": "Districts",
        "about.readFirst": "Read this first",
        "about.attribution": "Where the shape of this data comes from",
        "about.howNumbers": "How the numbers are worked out",
        "about.bullet1": "Cases and deaths are counts reported by hospitals, so they undercount people who never went to one.",
        "about.bullet2": "Patients in hospital is a census — how many beds are occupied on that day — not a running total.",
        "about.bullet3": "The 7-day average smooths the dip in reporting on Friday and Saturday.",
        "about.bullet4": "Risk bands use 14-day cases per 100,000 residents: under 5 low, 5 to 20 moderate, 20 to 60 high, above 60 severe.",
        "about.bullet5": "Case fatality rate is deaths divided by reported cases, which overstates the true rate because mild cases go unreported.",
        "about.medical": "Medical disclaimer",
        "about.medicalDetail": "DengueWatch does not diagnose or treat anything. The symptom check follows WHO dengue warning-sign criteria to help you decide when to seek care — it is not a substitute for seeing a clinician.",
        "about.privacy": "Privacy",
        "about.privacyDetail": "Your district, your settings and your symptom log stay on this device. The app makes no account and sends no analytics. Location is used only on the phone, to find hospitals near you and to notice when you enter a high-risk district.",
        "about.sync": "Updates",
        "about.goingLive": "Going live",
        "about.goingLiveDetail": "The app reads its data through a single service protocol. Point RemoteSurveillanceService at a real DGHS-shaped endpoint and every screen updates without further change.",
        "about.language": "Language",

        "intro.title": "Before you start",
        "intro.p1.title": "These are real DGHS figures.",
        "intro.p1.detail": "Compiled from the Directorate General of Health Services' daily dengue press releases.",
        "intro.p2.title": "They count hospital patients only.",
        "intro.p2.detail": "Anyone who had dengue but never went to a hospital is not in these numbers, so the true burden is higher.",
        "intro.p3.title": "This app cannot diagnose dengue.",
        "intro.p3.detail": "The symptom check follows WHO warning-sign criteria to help you decide when to seek care.",
        "intro.p4.title": "Nothing you enter leaves your phone.",
        "intro.p4.detail": "No account, no analytics. Location is used on the device only.",
        "intro.understand": "I understand",
        "intro.language": "Choose your language",
    ]

    static let bnAbout: [String: String] = [
        "about.title": "এই তথ্য সম্পর্কে",
        "about.build": "এই সংস্করণ",
        "about.dataset": "তথ্যভান্ডার",
        "about.lastUpdated": "সর্বশেষ হালনাগাদ",
        "about.seasonStart": "মৌসুম শুরু",
        "about.districts": "জেলা",
        "about.readFirst": "প্রথমেই পড়ুন",
        "about.attribution": "এই তথ্যের কাঠামো কোথা থেকে এসেছে",
        "about.howNumbers": "সংখ্যাগুলো যেভাবে হিসাব করা হয়",
        "about.bullet1": "আক্রান্ত ও মৃত্যুর সংখ্যা হাসপাতাল থেকে জানানো হিসাব, তাই যাঁরা কখনো হাসপাতালে যাননি তাঁরা এতে ধরা পড়েন না।",
        "about.bullet2": "হাসপাতালে ভর্তি রোগী মানে ওই দিনে কতটি শয্যা ভরা ছিল — এটি ক্রমযোগ হিসাব নয়।",
        "about.bullet3": "৭ দিনের গড় শুক্র ও শনিবারে রিপোর্ট কমে যাওয়ার প্রভাব মসৃণ করে।",
        "about.bullet4": "ঝুঁকির মাত্রা হিসাব হয় ১৪ দিনে প্রতি লাখ বাসিন্দায় রোগীর সংখ্যা দিয়ে: ৫-এর কম কম, ৫ থেকে ২০ মাঝারি, ২০ থেকে ৬০ বেশি, ৬০-এর বেশি তীব্র।",
        "about.bullet5": "মৃত্যুহার হলো মৃত্যু ভাগ শনাক্ত রোগী, যা প্রকৃত হারের চেয়ে বেশি দেখায় কারণ মৃদু রোগীরা হিসাবে আসেন না।",
        "about.medical": "চিকিৎসা সংক্রান্ত দাবিত্যাগ",
        "about.medicalDetail": "ডেঙ্গুওয়াচ কোনো রোগ নির্ণয় বা চিকিৎসা করে না। উপসর্গ পরীক্ষা বিশ্ব স্বাস্থ্য সংস্থার বিপদচিহ্নের নির্দেশনা অনুসরণ করে কেবল কখন চিকিৎসা নেওয়া দরকার তা বুঝতে সাহায্য করে — এটি চিকিৎসকের বিকল্প নয়।",
        "about.privacy": "গোপনীয়তা",
        "about.privacyDetail": "আপনার জেলা, সেটিংস ও উপসর্গের তালিকা এই ফোনেই থাকে। অ্যাপটি কোনো অ্যাকাউন্ট তৈরি করে না ও কোনো তথ্য পাঠায় না। অবস্থান কেবল ফোনের ভেতরেই ব্যবহার হয় — কাছাকাছি হাসপাতাল খুঁজতে এবং উচ্চঝুঁকির জেলায় ঢোকা বুঝতে।",
        "about.sync": "হালনাগাদ",
        "about.goingLive": "সরাসরি তথ্যে যাওয়া",
        "about.goingLiveDetail": "অ্যাপটি একটিমাত্র সার্ভিস প্রোটোকলের মাধ্যমে তথ্য পড়ে। RemoteSurveillanceService-কে স্বাস্থ্য অধিদপ্তরের কাঠামোর একটি সত্যিকারের ঠিকানায় যুক্ত করলেই সব পর্দা আপনাআপনি হালনাগাদ হবে।",
        "about.language": "ভাষা",

        "intro.title": "শুরু করার আগে",
        "intro.p1.title": "এগুলো স্বাস্থ্য অধিদপ্তরের প্রকৃত সংখ্যা।",
        "intro.p1.detail": "স্বাস্থ্য অধিদপ্তরের দৈনিক ডেঙ্গু প্রেস রিলিজ থেকে সংকলিত।",
        "intro.p2.title": "এতে কেবল হাসপাতালের রোগীরাই আছেন।",
        "intro.p2.detail": "যাঁদের ডেঙ্গু হয়েছিল কিন্তু হাসপাতালে যাননি, তাঁরা এই হিসাবে নেই — তাই প্রকৃত সংখ্যা আরও বেশি।",
        "intro.p3.title": "এই অ্যাপ ডেঙ্গু নির্ণয় করতে পারে না।",
        "intro.p3.detail": "উপসর্গ পরীক্ষা বিশ্ব স্বাস্থ্য সংস্থার বিপদচিহ্ন অনুসরণ করে কেবল কখন চিকিৎসা নেবেন তা বুঝতে সাহায্য করে।",
        "intro.p4.title": "আপনার দেওয়া কোনো তথ্য ফোন থেকে বের হয় না।",
        "intro.p4.detail": "কোনো অ্যাকাউন্ট নেই, কোনো তথ্য পাঠানো হয় না। অবস্থান শুধু ফোনেই ব্যবহার হয়।",
        "intro.understand": "আমি বুঝেছি",
        "intro.language": "আপনার ভাষা বাছুন",
    ]
}
