import Foundation

extension Strings {
    static let enRedesign: [String: String] = [
        "tab.home": "Home",

        "risk.card.title": "Dengue risk",
        "risk.card.hint": "Opens an explanation of how this risk level is worked out",
        "risk.card.updated": "Updated %@",
        "risk.trend.rising": "Increasing",
        "risk.trend.falling": "Decreasing",
        "risk.trend.steady": "Holding steady",
        "risk.detail.how": "How this is worked out",
        "risk.detail.window": "Cases in the last 14 days",
        "risk.detail.bands": "The four bands",
        "risk.detail.band.0": "Under 5 cases per 100,000 in 14 days",
        "risk.detail.band.1": "5 to 20 per 100,000",
        "risk.detail.band.2": "20 to 60 per 100,000",
        "risk.detail.band.3": "Above 60 per 100,000",

        "area.nationwide": "Bangladesh",
        "area.chooseHint": "Choose your area for a local reading",

        "activity.title": "Dengue activity",
        "activity.subtitle": "Nationwide, this season",
        "activity.thisWeek": "Cases this week",
        "activity.hotspots": "High-risk areas",
        "activity.hotspotsCaption": "of 64",
        "activity.since": "since %@",
        "risk.a11y.rate": "%@ cases per 100,000 over 14 days",
        "dash.stale.message": "These are the last figures we downloaded. Pull down to try again.",
        "trend.windowTotal": "in %@",
        "stale.title": "These figures may be out of date",
        "stale.message": "The newest DGHS report we have is %@ days old. DGHS publishes daily, so an update is probably not reaching the app.",
        "outdated.title": "These figures are too old to rely on",
        "map.asOf": "Map data current as of %@.",
        "outdated.message": "The newest DGHS report we have is %@ days old. Treat these numbers as history, not as the current situation.",
        "stale.checkFailed": "Today's check of the DGHS source did not succeed, so this is the last data we were able to get.",
        "locperm.title": "Show dengue risk around you",
        "locperm.body": "DengueWatch uses your location to show the risk where you actually are.",
        "locperm.reason1": "See which area you are in and its current risk band.",
        "locperm.reason2": "Find the nearest hospitals when you need care.",
        "locperm.reason3": "Your location is checked on this phone and never uploaded.",
        "locperm.allow": "Use my location",
        "locperm.notNow": "Not now",
        "geo.prompt.title": "Warn me when I enter a high-risk area",
        "geo.prompt.body": "Get a notification if you travel into an area with high dengue transmission.",
        "geo.prompt.enable": "Turn on",
        "geo.prompt.enabled": "Alerts on for high-risk areas",

        "trend.section": "Trend",
        "trend.title": "Reported cases",
        "trend.subtitle": "Daily, with a 7-day average",
        "trend.range.week": "7D",
        "trend.range.fortnight": "14D",
        "trend.range.month": "30D",

        "map.section": "Where it is spreading",
        "map.preview.a11y": "Map preview showing the highest-risk areas. Opens the full risk map.",

        "guidance.title": "What you can do",
        "guidance.check": "Check symptoms",
        "guidance.care": "Find care",
        "guidance.prevent": "Prevent",

        "alert.viewMap": "View risk map",
        "alert.highArea.title": "High-risk area",
        "alert.highArea.message": "Dengue activity in %@ is high. Use repellent, cover up during the day, and treat any fever as possible dengue.",
        "alert.rising.title": "Cases are rising",
        "alert.rising.message": "Reported cases are up %@ on last week nationwide.",

        "source.official": "Official data",
        "source.guidance": "Health guidance",

        "dash.error.message": "We couldn't load the latest dengue figures. Your last downloaded data is still available offline.",
        "common.viewAll": "View all",

        "map.state.loading": "Loading the risk map…",
        "map.state.emptyTitle": "No area data yet",
        "map.state.emptyMessage": "Dengue figures for this season have not been published yet. They appear here as soon as they are.",
        "map.area.recentCases": "Cases in the last 7 days",
        "map.area.seasonCases": "Cases this season",
        "map.area.rate": "14-day rate",
        "map.area.viewDetail": "See full area page",
        "map.area.setHome": "Use as my area",

        "location.why.title": "Show risk where you are",
        "location.why.message": "DengueWatch uses your location to show the dengue risk around you and to find hospitals nearby. Your location stays on this phone.",
        "location.why.allow": "Allow location",
        "location.why.manual": "Choose an area instead",
        "location.denied.title": "Location is off",
        "location.denied.message": "You can still use DengueWatch by choosing your area manually.",
    ]

    static let bnRedesign: [String: String] = [
        "tab.home": "হোম",

        "risk.card.title": "ডেঙ্গু ঝুঁকি",
        "risk.card.hint": "এই ঝুঁকির মাত্রা কীভাবে হিসাব করা হয় তার ব্যাখ্যা খোলে",
        "risk.card.updated": "হালনাগাদ %@",
        "risk.trend.rising": "বাড়ছে",
        "risk.trend.falling": "কমছে",
        "risk.trend.steady": "স্থিতিশীল",
        "risk.detail.how": "যেভাবে হিসাব করা হয়",
        "risk.detail.window": "গত ১৪ দিনে রোগী",
        "risk.detail.bands": "চারটি মাত্রা",
        "risk.detail.band.0": "১৪ দিনে প্রতি লাখে ৫-এর কম",
        "risk.detail.band.1": "প্রতি লাখে ৫ থেকে ২০",
        "risk.detail.band.2": "প্রতি লাখে ২০ থেকে ৬০",
        "risk.detail.band.3": "প্রতি লাখে ৬০-এর বেশি",

        "area.nationwide": "বাংলাদেশ",
        "area.chooseHint": "নিজের এলাকার তথ্য পেতে এলাকা বাছুন",

        "activity.title": "ডেঙ্গু পরিস্থিতি",
        "activity.subtitle": "সারা দেশে, এ মৌসুমে",
        "activity.thisWeek": "এ সপ্তাহে রোগী",
        "activity.hotspots": "উচ্চঝুঁকির এলাকা",
        "activity.hotspotsCaption": "৬৪টির মধ্যে",
        "activity.since": "%@ থেকে",
        "risk.a11y.rate": "১৪ দিনে প্রতি লাখে %@ জন",
        "dash.stale.message": "এগুলো সর্বশেষ নামানো তথ্য। আবার চেষ্টা করতে নিচে টানুন।",
        "trend.windowTotal": "%@-এ",
        "stale.title": "এই সংখ্যা পুরনো হতে পারে",
        "stale.message": "আমাদের কাছে থাকা সর্বশেষ স্বাস্থ্য অধিদপ্তরের প্রতিবেদন %@ দিনের পুরনো। প্রতিদিন প্রতিবেদন প্রকাশিত হয়, তাই সম্ভবত হালনাগাদ অ্যাপে পৌঁছাচ্ছে না।",
        "outdated.title": "এই সংখ্যা এতটাই পুরনো যে ভরসা করা যায় না",
        "map.asOf": "মানচিত্রের তথ্য %@ পর্যন্ত হালনাগাদ।",
        "outdated.message": "আমাদের কাছে থাকা সর্বশেষ স্বাস্থ্য অধিদপ্তরের প্রতিবেদন %@ দিনের পুরনো। এগুলোকে বর্তমান পরিস্থিতি নয়, অতীতের তথ্য হিসেবে দেখুন।",
        "stale.checkFailed": "আজ স্বাস্থ্য অধিদপ্তরের উৎস যাচাই করা যায়নি, তাই এটাই আমাদের পাওয়া সর্বশেষ তথ্য।",
        "locperm.title": "আপনার আশপাশের ডেঙ্গু ঝুঁকি দেখুন",
        "locperm.body": "আপনি আসলে যেখানে আছেন সেখানকার ঝুঁকি দেখাতে ডেঙ্গুওয়াচ আপনার অবস্থান ব্যবহার করে।",
        "locperm.reason1": "আপনি কোন এলাকায় আছেন এবং সেখানকার ঝুঁকি কত তা দেখুন।",
        "locperm.reason2": "প্রয়োজনের সময় নিকটতম হাসপাতাল খুঁজুন।",
        "locperm.reason3": "আপনার অবস্থান এই ফোনেই যাচাই হয়, কোথাও পাঠানো হয় না।",
        "locperm.allow": "আমার অবস্থান ব্যবহার করুন",
        "locperm.notNow": "এখন নয়",
        "geo.prompt.title": "উচ্চঝুঁকির এলাকায় ঢুকলে সতর্ক করুন",
        "geo.prompt.body": "উচ্চ ডেঙ্গু সংক্রমণের এলাকায় গেলে নোটিফিকেশন পাবেন।",
        "geo.prompt.enable": "চালু করুন",
        "geo.prompt.enabled": "উচ্চঝুঁকির এলাকার সতর্কবার্তা চালু আছে",

        "trend.section": "গতিপ্রকৃতি",
        "trend.title": "শনাক্ত রোগী",
        "trend.subtitle": "দৈনিক, সঙ্গে ৭ দিনের গড়",
        "trend.range.week": "৭ দিন",
        "trend.range.fortnight": "১৪ দিন",
        "trend.range.month": "৩০ দিন",

        "map.section": "কোথায় ছড়াচ্ছে",
        "map.preview.a11y": "সর্বোচ্চ ঝুঁকির এলাকাগুলোর মানচিত্রের সংক্ষিপ্ত রূপ। পূর্ণ ঝুঁকির মানচিত্র খোলে।",

        "guidance.title": "আপনি যা করতে পারেন",
        "guidance.check": "উপসর্গ দেখুন",
        "guidance.care": "চিকিৎসা খুঁজুন",
        "guidance.prevent": "প্রতিরোধ",

        "alert.viewMap": "ঝুঁকির মানচিত্র দেখুন",
        "alert.highArea.title": "উচ্চঝুঁকির এলাকা",
        "alert.highArea.message": "%@ এলাকায় ডেঙ্গুর প্রকোপ বেশি। মশা প্রতিরোধক ব্যবহার করুন, দিনের বেলা শরীর ঢেকে রাখুন এবং যেকোনো জ্বরকে ডেঙ্গু ধরে নিন।",
        "alert.rising.title": "রোগীর সংখ্যা বাড়ছে",
        "alert.rising.message": "সারা দেশে গত সপ্তাহের তুলনায় শনাক্ত রোগী %@ বেড়েছে।",

        "source.official": "সরকারি তথ্য",
        "source.guidance": "স্বাস্থ্য নির্দেশনা",

        "dash.error.message": "সর্বশেষ ডেঙ্গুর হিসাব আনা যায়নি। আগে নামানো তথ্য এখনো অফলাইনে দেখা যাচ্ছে।",
        "common.viewAll": "সব দেখুন",

        "map.state.loading": "ঝুঁকির মানচিত্র লোড হচ্ছে…",
        "map.state.emptyTitle": "এখনো এলাকাভিত্তিক তথ্য নেই",
        "map.state.emptyMessage": "এ মৌসুমের ডেঙ্গুর হিসাব এখনো প্রকাশিত হয়নি। প্রকাশিত হলেই এখানে দেখা যাবে।",
        "map.area.recentCases": "গত ৭ দিনে রোগী",
        "map.area.seasonCases": "এ মৌসুমে রোগী",
        "map.area.rate": "১৪ দিনের হার",
        "map.area.viewDetail": "এলাকার পূর্ণ তথ্য দেখুন",
        "map.area.setHome": "আমার এলাকা হিসেবে নিন",

        "location.why.title": "আপনি যেখানে আছেন সেখানকার ঝুঁকি দেখুন",
        "location.why.message": "আপনার আশপাশের ডেঙ্গু ঝুঁকি দেখাতে এবং কাছাকাছি হাসপাতাল খুঁজতে ডেঙ্গুওয়াচ আপনার অবস্থান ব্যবহার করে। আপনার অবস্থান এই ফোনেই থাকে।",
        "location.why.allow": "অবস্থানের অনুমতি দিন",
        "location.why.manual": "বরং এলাকা বাছাই করুন",
        "location.denied.title": "অবস্থান বন্ধ আছে",
        "location.denied.message": "এলাকা নিজে বাছাই করেও আপনি ডেঙ্গুওয়াচ ব্যবহার করতে পারবেন।",
    ]
}
