import Foundation

extension Strings {
    static let enMap: [String: String] = [
        "area.apportioned.note": "Weekly figures for the Dhaka city corporations are shared out from the Dhaka division series, which is the finest weekly breakdown DGHS publishes. Season cases and deaths are reported for this area directly.",
        "map.title": "Where it is spreading",
        "map.metric.total": "Total cases",
        "map.metric.rate": "Per 100k",
        "map.explain.total": "Circle area is the season total. Big cities dominate simply because more people live in them.",
        "map.explain.rate": "Circle area is two-week cases per 100,000 residents, which is comparable between a city corporation and a large division.",
        "map.legend.risk": "14-day risk",
        "map.showList": "Show list",
        "map.showMap": "Show map",
        "map.search": "Search area or division",
        "map.list.divisions": "By division · season cases",
        "map.list.areas": "All reporting areas · season cases",
        "map.list.footer": "Risk is 14-day reported cases per 100,000 residents: under 5 low, 5–20 moderate, 20–60 high, above 60 severe.",
        "map.bubble.a11y": "%@, %@ cases, %@ risk",
        "map.you.inArea": "You are in %@",
        "map.you.enable": "Show my location",
        "map.you.denied": "Location is off. Turn it on for DengueWatch in Settings to see where you are on the map.",
        "map.you.locating": "Finding your location…",
        "map.you.wholeCountry": "Show the whole country",
        "map.you.outside": "You are outside the area this map covers.",

        "area.division": "%@ division",
        "area.population": "About %@ residents",
        "area.setHome": "Set as my area",
        "area.isHome": "This is your home area",
        "area.stat.season": "Season cases",
        "area.stat.last7": "Latest week",
        "area.stat.rate": "Two-week rate",
        "area.stat.deaths": "Season deaths",
        "area.rank": "#%@ of 10 areas",
        "area.riskBand": "%@ risk band",
        "area.share": "%@%% of national cases",
        "area.chart.title": "Cases in %@",
        "area.chart.subtitle": "Cases by epidemiological week, with a 3-week average",
        "area.peers.title": "Rest of %@ division",
        "area.peers.subtitle": "Season cases in neighbouring areas",
        "area.picker.title": "My area",
        "area.picker.search": "Search areas",
    ]

    static let bnMap: [String: String] = [
        "area.apportioned.note": "ঢাকার সিটি করপোরেশনগুলোর সাপ্তাহিক হিসাব ঢাকা বিভাগের সিরিজ থেকে ভাগ করে বের করা — স্বাস্থ্য অধিদপ্তর সাপ্তাহিক হিসাব এর চেয়ে সূক্ষ্মভাবে প্রকাশ করে না। মৌসুমের রোগী ও মৃত্যু সরাসরি এই এলাকার জন্যই জানানো।",
        "map.title": "কোথায় ছড়াচ্ছে",
        "map.metric.total": "মোট রোগী",
        "map.metric.rate": "প্রতি লাখে",
        "map.explain.total": "বৃত্তের আকার মৌসুমের মোট রোগী। বড় শহর এগিয়ে থাকে শুধু বেশি মানুষ থাকার কারণে।",
        "map.explain.rate": "বৃত্তের আকার দুই সপ্তাহে প্রতি লাখ বাসিন্দায় রোগীর সংখ্যা, যা সিটি করপোরেশন ও বড় বিভাগের মধ্যে তুলনাযোগ্য।",
        "map.legend.risk": "১৪ দিনের ঝুঁকি",
        "map.showList": "তালিকা দেখুন",
        "map.showMap": "মানচিত্র দেখুন",
        "map.search": "এলাকা বা বিভাগ খুঁজুন",
        "map.list.divisions": "বিভাগ অনুযায়ী · মৌসুমের রোগী",
        "map.list.areas": "সব রিপোর্টিং এলাকা · মৌসুমের রোগী",
        "map.list.footer": "ঝুঁকি হিসাব করা হয় ১৪ দিনে প্রতি লাখ বাসিন্দায় শনাক্ত রোগী দিয়ে: ৫-এর কম কম, ৫–২০ মাঝারি, ২০–৬০ বেশি, ৬০-এর বেশি তীব্র।",
        "map.bubble.a11y": "%@, %@ জন আক্রান্ত, ঝুঁকি %@",
        "map.you.inArea": "আপনি আছেন %@ এলাকায়",
        "map.you.enable": "আমার অবস্থান দেখান",
        "map.you.denied": "অবস্থান বন্ধ আছে। মানচিত্রে নিজের অবস্থান দেখতে সেটিংসে গিয়ে ডেঙ্গুওয়াচের জন্য চালু করুন।",
        "map.you.locating": "আপনার অবস্থান খোঁজা হচ্ছে…",
        "map.you.wholeCountry": "পুরো দেশ দেখুন",
        "map.you.outside": "এই মানচিত্র যে এলাকা দেখায়, আপনি তার বাইরে আছেন।",

        "area.division": "%@ বিভাগ",
        "area.population": "প্রায় %@ জন বাসিন্দা",
        "area.setHome": "আমার এলাকা হিসেবে নির্ধারণ করুন",
        "area.isHome": "এটি আপনার নিজের এলাকা",
        "area.stat.season": "মৌসুমের রোগী",
        "area.stat.last7": "সর্বশেষ সপ্তাহ",
        "area.stat.rate": "দুই সপ্তাহের হার",
        "area.stat.deaths": "মৌসুমের মৃত্যু",
        "area.rank": "১০ এলাকার মধ্যে %@ নম্বর",
        "area.riskBand": "ঝুঁকি %@",
        "area.share": "জাতীয় রোগীর %@%%",
        "area.chart.title": "%@ এলাকার রোগী",
        "area.chart.subtitle": "সপ্তাহভিত্তিক রোগী, সঙ্গে ৩ সপ্তাহের গড়",
        "area.peers.title": "%@ বিভাগের অন্যান্য এলাকা",
        "area.peers.subtitle": "পার্শ্ববর্তী এলাকাগুলোতে মৌসুমের রোগী",
        "area.picker.title": "আমার এলাকা",
        "area.picker.search": "এলাকা খুঁজুন",
    ]
}
