import Foundation

extension Strings {
    static let enPrevent: [String: String] = [
        "prevent.title": "Prevention",
        "prevent.season.title": "The dengue year in Bangladesh",
        "prevent.season.subtitle": "When transmission usually rises and falls",
        "prevent.season.footnote": "Bars show the typical seasonal pattern, not this year's data. The marked month is now.",
        "prevent.month.jan": "Jan", "prevent.month.feb": "Feb", "prevent.month.mar": "Mar",
        "prevent.month.apr": "Apr", "prevent.month.may": "May", "prevent.month.jun": "Jun",
        "prevent.month.jul": "Jul", "prevent.month.aug": "Aug", "prevent.month.sep": "Sep",
        "prevent.month.oct": "Oct", "prevent.month.nov": "Nov", "prevent.month.dec": "Dec",
        "prevent.note.jan": "Cool and dry. Very little transmission.",
        "prevent.note.feb": "Lowest point of the year.",
        "prevent.note.mar": "Pre-monsoon showers begin to leave water standing.",
        "prevent.note.apr": "Containers start filling. A good month to clear them.",
        "prevent.note.may": "Pre-monsoon rain; case counts start to move.",
        "prevent.note.jun": "Monsoon arrives and breeding sites multiply.",
        "prevent.note.jul": "Cases climb steeply through the month.",
        "prevent.note.aug": "Peak season begins; hospitals fill.",
        "prevent.note.sep": "Usually the worst month of the year.",
        "prevent.note.oct": "Still very high; post-monsoon water everywhere.",
        "prevent.note.nov": "Falling, but a long tail of cases continues.",
        "prevent.note.dec": "Winter brings transmission down sharply.",

        "prevent.breeding.title": "Kill the breeding sites",
        "prevent.breeding.summary": "Aedes lays eggs in clean, still water — almost always inside or right beside your own home. One neglected container can produce hundreds of mosquitoes.",
        "prevent.breeding.step1": "Empty and scrub water from flower pot trays, buckets, drums and the fridge drip tray once a week. Scrubbing matters: eggs stick to the sides and survive drying.",
        "prevent.breeding.step2": "Cover every water storage tank and drum with a tight lid or fine mesh.",
        "prevent.breeding.step3": "Clear blocked roof gutters and flat rooftops after rain.",
        "prevent.breeding.step4": "Throw out or turn over tyres, coconut shells, broken pots and plastic cups in the yard.",
        "prevent.breeding.step5": "Change water in vases and animal bowls every two days.",
        "prevent.breeding.step6": "Put a little sand in the bases of air-conditioner and water cooler drip trays so water cannot pool.",

        "prevent.bites.title": "Avoid being bitten",
        "prevent.bites.summary": "This mosquito bites in daylight, with peaks in the two hours after sunrise and the hours before dusk. A net at night alone is not enough.",
        "prevent.bites.step1": "Use a repellent with DEET, picaridin or oil of lemon eucalyptus on exposed skin during the day.",
        "prevent.bites.step2": "Wear long sleeves and long trousers, ideally light coloured, in the morning and late afternoon.",
        "prevent.bites.step3": "Fit screens on windows and doors, and repair torn ones.",
        "prevent.bites.step4": "Sleep under a mosquito net during daytime naps, especially for children, older people and anyone already ill.",
        "prevent.bites.step5": "Use a net or screened room for anyone with a fever, so they cannot pass the virus to a mosquito that then bites the family.",

        "prevent.care.title": "Caring for someone with dengue",
        "prevent.care.summary": "Most dengue is managed at home with fluids and rest. The danger window is when the fever falls, not when it is highest.",
        "prevent.care.step1": "Paracetamol only for fever and pain. No aspirin, ibuprofen, diclofenac or other NSAIDs — they increase bleeding risk.",
        "prevent.care.step2": "Fluids through the day: oral rehydration solution, coconut water, rice water, soup, milk. Plain water alone is not ideal.",
        "prevent.care.step3": "Track urine — passing urine every 4 to 6 hours is a good sign that hydration is adequate.",
        "prevent.care.step4": "Watch for warning signs from day 3 to day 7, especially as the fever drops.",
        "prevent.care.step5": "Do not take antibiotics or steroids unless a doctor prescribes them; they do nothing for dengue.",
        "prevent.care.step6": "Keep the patient under a net so the infection does not spread to the rest of the household.",

        "prevent.community.title": "Your street and neighbourhood",
        "prevent.community.summary": "Because the mosquito flies such short distances, clearing one building is worth more than any city-wide measure taken alone.",
        "prevent.community.step1": "Agree a weekly ten-minute container check with neighbours — the same day each week works best.",
        "prevent.community.step2": "Report standing water, blocked drains and abandoned construction sites to your city corporation ward office.",
        "prevent.community.step3": "Construction sites, rooftops and empty flats are the usual sources on a street; ask a caretaker to check them.",
        "prevent.community.step4": "Fogging kills adult mosquitoes for a day or two only. It is not a substitute for removing water.",
        "prevent.community.step5": "Push for larvicide treatment of drains and tanks that genuinely cannot be emptied.",

        "prevent.testing.title": "Testing and when to go in",
        "prevent.testing.summary": "Testing early changes what a clinician can do for you, and a platelet count is not the only thing that matters.",
        "prevent.testing.step1": "NS1 antigen test: most reliable in the first 5 days of fever.",
        "prevent.testing.step2": "IgM/IgG antibody test: useful from about day 5 onward.",
        "prevent.testing.step3": "A packed cell volume (haematocrit) trend matters as much as the platelet count — a rising haematocrit with a falling platelet count signals plasma leak.",
        "prevent.testing.step4": "Go in the same day for any warning sign: bad stomach pain, repeated vomiting, bleeding, breathlessness, sudden weakness, or little urine.",
        "prevent.testing.step5": "Free or subsidised dengue testing is offered at government hospitals and many city corporation centres during outbreak season.",

        "alerts.entry": "Alerts for my area",
        "alerts.on": "On — you will be told when your area reaches %@ risk",
        "alerts.off": "Off — turn on to hear when your area gets worse",
        "alerts.title": "Alerts",
        "alerts.myArea": "My area",
        "alerts.noArea": "No area chosen yet",
        "alerts.chooseArea": "Choose area",
        "alerts.areaFooter": "Alerts are worked out on this phone from the data already downloaded. Your area is never sent anywhere.",
        "alerts.notifications": "Notifications",
        "alerts.riseToggle": "Alert me when risk rises",
        "alerts.threshold": "Tell me at",
        "alerts.thresholdOption": "%@ risk and above",
        "alerts.weekly": "Weekly summary on Sunday morning",
        "alerts.footer": "At most one risk alert a day. Risk bands use 14-day cases per 100,000 residents.",
        "alerts.preview": "What you would be told right now",
        "alerts.preview.would": "%@ is at %@ risk — you would get an alert.",
        "alerts.preview.wouldNot": "%@ is at %@ risk, below your threshold. No alert.",
        "alerts.denied.title": "Notifications are turned off",
        "alerts.denied.message": "Allow notifications for DengueWatch in Settings to get area alerts.",

        "geo.section": "Alerts where you are",
        "geo.toggle": "Warn me when I enter a high-risk area",
        "geo.footer": "Uses your location in the background to notice when you cross into an area in the high or severe band. Your location is checked on this phone and is never uploaded.",
        "geo.permission": "Allow background location",
        "geo.permissionDetail": "iOS asks for \"Always\" permission for this. Without it the warning only works while DengueWatch is open.",
        "geo.notification.title": "You are entering %@",
        "geo.notification.body": "%@ is in the %@ risk band, with %@ cases reported in the last 7 days. Use repellent and cover up.",
        "geo.status.off": "Off",
        "geo.status.foreground": "Only while the app is open",
        "geo.status.always": "On, including in the background",
        "geo.monitoring": "Watching %@ high-risk areas",
    ]

    static let bnPrevent: [String: String] = [
        "prevent.title": "প্রতিরোধ",
        "prevent.season.title": "বাংলাদেশে ডেঙ্গুর বছর",
        "prevent.season.subtitle": "সাধারণত কখন সংক্রমণ বাড়ে ও কমে",
        "prevent.season.footnote": "বারগুলো সাধারণ মৌসুমি ধারা দেখায়, এ বছরের তথ্য নয়। চিহ্ন দেওয়া মাসটি এখনকার।",
        "prevent.month.jan": "জানু", "prevent.month.feb": "ফেব্রু", "prevent.month.mar": "মার্চ",
        "prevent.month.apr": "এপ্রিল", "prevent.month.may": "মে", "prevent.month.jun": "জুন",
        "prevent.month.jul": "জুলাই", "prevent.month.aug": "আগস্ট", "prevent.month.sep": "সেপ্ট",
        "prevent.month.oct": "অক্টো", "prevent.month.nov": "নভে", "prevent.month.dec": "ডিসে",
        "prevent.note.jan": "ঠান্ডা ও শুষ্ক। সংক্রমণ খুব কম।",
        "prevent.note.feb": "বছরের সবচেয়ে কম সময়।",
        "prevent.note.mar": "প্রাক-বর্ষার বৃষ্টিতে পানি জমতে শুরু করে।",
        "prevent.note.apr": "পাত্রে পানি জমতে শুরু করে। পরিষ্কার করার উপযুক্ত সময়।",
        "prevent.note.may": "প্রাক-বর্ষার বৃষ্টি; রোগীর সংখ্যা বাড়তে শুরু করে।",
        "prevent.note.jun": "বর্ষা আসে এবং প্রজননস্থল বহুগুণ বাড়ে।",
        "prevent.note.jul": "এ মাসে রোগীর সংখ্যা দ্রুত বাড়ে।",
        "prevent.note.aug": "সর্বোচ্চ মৌসুম শুরু; হাসপাতাল ভরে যায়।",
        "prevent.note.sep": "সাধারণত বছরের সবচেয়ে খারাপ মাস।",
        "prevent.note.oct": "এখনো অনেক বেশি; বর্ষা-পরবর্তী পানি সর্বত্র।",
        "prevent.note.nov": "কমছে, তবে রোগী আসতে থাকে অনেক দিন।",
        "prevent.note.dec": "শীতে সংক্রমণ দ্রুত কমে যায়।",

        "prevent.breeding.title": "প্রজননস্থল ধ্বংস করুন",
        "prevent.breeding.summary": "এডিস মশা পরিষ্কার, স্থির পানিতে ডিম পাড়ে — প্রায় সবসময় আপনার ঘরের ভেতরে বা ঠিক পাশেই। একটি অবহেলিত পাত্র থেকেই শত শত মশা জন্মাতে পারে।",
        "prevent.breeding.step1": "সপ্তাহে একবার ফুলের টবের নিচের প্লেট, বালতি, ড্রাম ও ফ্রিজের ট্রে খালি করে ঘষে পরিষ্কার করুন। ঘষা জরুরি: ডিম পাত্রের গায়ে লেগে থাকে এবং শুকিয়ে গেলেও বেঁচে থাকে।",
        "prevent.breeding.step2": "প্রতিটি পানির ট্যাংক ও ড্রাম শক্ত ঢাকনা বা মিহি জাল দিয়ে ঢেকে রাখুন।",
        "prevent.breeding.step3": "বৃষ্টির পর ছাদের নালা ও সমতল ছাদের জমা পানি সরান।",
        "prevent.breeding.step4": "উঠানের পুরনো টায়ার, নারকেলের খোল, ভাঙা পাত্র ও প্লাস্টিকের কাপ ফেলে দিন বা উল্টে রাখুন।",
        "prevent.breeding.step5": "ফুলদানি ও পশুপাখির পানির পাত্রের পানি দুদিন পরপর বদলান।",
        "prevent.breeding.step6": "এসি ও ওয়াটার কুলারের ট্রেতে সামান্য বালি দিয়ে রাখুন যাতে পানি জমতে না পারে।",

        "prevent.bites.title": "মশার কামড় এড়ান",
        "prevent.bites.summary": "এই মশা দিনের বেলায় কামড়ায়, বিশেষত সূর্যোদয়ের পরের দুই ঘণ্টা ও সন্ধ্যার আগের সময়ে। শুধু রাতে মশারি ব্যবহার যথেষ্ট নয়।",
        "prevent.bites.step1": "দিনের বেলায় খোলা ত্বকে ডিইইটি, পিকারিডিন বা লেমন ইউক্যালিপটাস তেলযুক্ত প্রতিরোধক ব্যবহার করুন।",
        "prevent.bites.step2": "সকাল ও বিকেলে হাতা-পা ঢাকা, বিশেষত হালকা রঙের পোশাক পরুন।",
        "prevent.bites.step3": "জানালা ও দরজায় নেট লাগান এবং ছেঁড়া নেট মেরামত করুন।",
        "prevent.bites.step4": "দিনের ঘুমেও মশারি ব্যবহার করুন, বিশেষত শিশু, বয়স্ক ও অসুস্থদের জন্য।",
        "prevent.bites.step5": "জ্বরে আক্রান্ত ব্যক্তিকে মশারির নিচে রাখুন, যাতে মশা তাঁকে কামড়ে পরিবারের অন্যদের মধ্যে ভাইরাস ছড়াতে না পারে।",

        "prevent.care.title": "ডেঙ্গু রোগীর যত্ন",
        "prevent.care.summary": "বেশিরভাগ ডেঙ্গু ঘরে বসেই পানি ও বিশ্রামে সামলানো যায়। বিপদের সময় জ্বর কমার মুহূর্ত, জ্বর সবচেয়ে বেশি থাকার সময় নয়।",
        "prevent.care.step1": "জ্বর ও ব্যথার জন্য শুধু প্যারাসিটামল। অ্যাসপিরিন, আইবুপ্রোফেন, ডাইক্লোফেনাক বা অন্য এনএসএআইডি নয় — এগুলো রক্তক্ষরণের ঝুঁকি বাড়ায়।",
        "prevent.care.step2": "সারা দিন তরল: খাবার স্যালাইন, ডাবের পানি, চালের মাড়, স্যুপ, দুধ। শুধু সাধারণ পানি যথেষ্ট নয়।",
        "prevent.care.step3": "প্রস্রাবের দিকে খেয়াল রাখুন — প্রতি ৪ থেকে ৬ ঘণ্টায় প্রস্রাব হলে বুঝবেন শরীরে পানি ঠিক আছে।",
        "prevent.care.step4": "৩ থেকে ৭ দিনের মধ্যে, বিশেষত জ্বর কমার সময় বিপদচিহ্নের দিকে নজর রাখুন।",
        "prevent.care.step5": "ডাক্তারের পরামর্শ ছাড়া অ্যান্টিবায়োটিক বা স্টেরয়েড খাবেন না; ডেঙ্গুতে এগুলো কোনো কাজে আসে না।",
        "prevent.care.step6": "রোগীকে মশারির নিচে রাখুন যাতে পরিবারের অন্যদের মধ্যে সংক্রমণ না ছড়ায়।",

        "prevent.community.title": "আপনার পাড়া ও এলাকা",
        "prevent.community.summary": "এই মশা খুব অল্প দূরত্বে ওড়ে বলে একটি ভবন পরিষ্কার করা পুরো শহরের যেকোনো একক পদক্ষেপের চেয়ে বেশি কাজে দেয়।",
        "prevent.community.step1": "প্রতিবেশীদের সঙ্গে সপ্তাহে দশ মিনিটের পাত্র পরীক্ষার দিন ঠিক করুন — প্রতি সপ্তাহে একই দিন হলে ভালো।",
        "prevent.community.step2": "জমা পানি, বন্ধ নালা ও পরিত্যক্ত নির্মাণস্থলের কথা সিটি করপোরেশনের ওয়ার্ড অফিসে জানান।",
        "prevent.community.step3": "নির্মাণস্থল, ছাদ ও খালি ফ্ল্যাটই সাধারণত উৎস; কেয়ারটেকারকে দেখতে বলুন।",
        "prevent.community.step4": "ফগিং শুধু এক-দুদিনের জন্য বড় মশা মারে। এটি জমা পানি সরানোর বিকল্প নয়।",
        "prevent.community.step5": "যেসব নালা ও ট্যাংক সত্যিই খালি করা যায় না, সেখানে লার্ভিসাইড দেওয়ার ব্যবস্থা করান।",

        "prevent.testing.title": "পরীক্ষা ও কখন হাসপাতালে যাবেন",
        "prevent.testing.summary": "আগেভাগে পরীক্ষা করালে চিকিৎসক অনেক বেশি কিছু করতে পারেন, আর প্লাটিলেটই একমাত্র বিবেচ্য বিষয় নয়।",
        "prevent.testing.step1": "এনএস১ অ্যান্টিজেন পরীক্ষা: জ্বরের প্রথম ৫ দিনে সবচেয়ে নির্ভরযোগ্য।",
        "prevent.testing.step2": "আইজিএম/আইজিজি অ্যান্টিবডি পরীক্ষা: প্রায় ৫ম দিন থেকে কার্যকর।",
        "prevent.testing.step3": "হেমাটোক্রিটের গতিপ্রকৃতি প্লাটিলেটের মতোই গুরুত্বপূর্ণ — হেমাটোক্রিট বাড়ার সঙ্গে প্লাটিলেট কমা মানে রক্তরস বেরিয়ে যাচ্ছে।",
        "prevent.testing.step4": "যেকোনো বিপদচিহ্ন দেখা দিলে সেদিনই যান: তীব্র পেটব্যথা, বারবার বমি, রক্তক্ষরণ, শ্বাসকষ্ট, হঠাৎ দুর্বলতা বা প্রস্রাব কমে যাওয়া।",
        "prevent.testing.step5": "প্রাদুর্ভাবের মৌসুমে সরকারি হাসপাতাল ও অনেক সিটি করপোরেশন কেন্দ্রে বিনামূল্যে বা কম খরচে ডেঙ্গু পরীক্ষা করা হয়।",

        "alerts.entry": "আমার এলাকার সতর্কবার্তা",
        "alerts.on": "চালু — আপনার এলাকা %@ ঝুঁকিতে পৌঁছালে জানানো হবে",
        "alerts.off": "বন্ধ — এলাকার অবস্থা খারাপ হলে জানতে চালু করুন",
        "alerts.title": "সতর্কবার্তা",
        "alerts.myArea": "আমার এলাকা",
        "alerts.noArea": "এখনো কোনো এলাকা বাছাই করা হয়নি",
        "alerts.chooseArea": "এলাকা বাছুন",
        "alerts.areaFooter": "সতর্কবার্তা এই ফোনেই আগে নামানো তথ্য থেকে হিসাব করা হয়। আপনার এলাকার তথ্য কোথাও পাঠানো হয় না।",
        "alerts.notifications": "নোটিফিকেশন",
        "alerts.riseToggle": "ঝুঁকি বাড়লে আমাকে জানান",
        "alerts.threshold": "কখন জানাবে",
        "alerts.thresholdOption": "%@ বা তার বেশি ঝুঁকি",
        "alerts.weekly": "রোববার সকালে সাপ্তাহিক সারসংক্ষেপ",
        "alerts.footer": "দিনে সর্বোচ্চ একটি সতর্কবার্তা। ঝুঁকি হিসাব হয় ১৪ দিনে প্রতি লাখ বাসিন্দায় রোগীর সংখ্যা দিয়ে।",
        "alerts.preview": "এই মুহূর্তে আপনাকে যা জানানো হতো",
        "alerts.preview.would": "%@ এখন %@ ঝুঁকিতে আছে — আপনি সতর্কবার্তা পেতেন।",
        "alerts.preview.wouldNot": "%@ এখন %@ ঝুঁকিতে, যা আপনার নির্ধারিত সীমার নিচে। কোনো সতর্কবার্তা নয়।",
        "alerts.denied.title": "নোটিফিকেশন বন্ধ আছে",
        "alerts.denied.message": "এলাকার সতর্কবার্তা পেতে সেটিংসে গিয়ে ডেঙ্গুওয়াচের নোটিফিকেশন চালু করুন।",

        "geo.section": "আপনি যেখানে আছেন সেখানকার সতর্কবার্তা",
        "geo.toggle": "উচ্চঝুঁকির এলাকায় ঢুকলে সতর্ক করুন",
        "geo.footer": "আপনি কখন উচ্চ বা তীব্র ঝুঁকির এলাকায় ঢুকছেন তা বুঝতে পটভূমিতে আপনার অবস্থান ব্যবহার করা হয়। অবস্থান এই ফোনেই যাচাই হয়, কোথাও পাঠানো হয় না।",
        "geo.permission": "পটভূমিতে অবস্থানের অনুমতি দিন",
        "geo.permissionDetail": "এর জন্য আইওএস \"সবসময়\" অনুমতি চায়। অনুমতি ছাড়া সতর্কবার্তা শুধু অ্যাপ খোলা থাকলেই কাজ করবে।",
        "geo.notification.title": "আপনি %@ এলাকায় ঢুকছেন",
        "geo.notification.body": "%@ এখন %@ ঝুঁকিতে, গত ৭ দিনে %@ জন আক্রান্ত হয়েছেন। মশা প্রতিরোধক ব্যবহার করুন ও শরীর ঢেকে রাখুন।",
        "geo.status.off": "বন্ধ",
        "geo.status.foreground": "শুধু অ্যাপ খোলা থাকলে",
        "geo.status.always": "চালু, পটভূমিতেও",
        "geo.monitoring": "%@টি উচ্চঝুঁকির এলাকার ওপর নজর রাখা হচ্ছে",
    ]
}
