import Foundation

extension Strings {
    static let enMap: [String: String] = [
        "map.title": "Where it is spreading",
        "map.metric.total": "Total cases",
        "map.metric.rate": "Per 100k",
        "map.explain.total": "Circle area is the season total. Big cities dominate simply because more people live in them.",
        "map.explain.rate": "Circle area is 14-day cases per 100,000 residents, which is comparable between a city and a small district.",
        "map.legend.risk": "14-day risk",
        "map.showList": "Show list",
        "map.showMap": "Show map",
        "map.search": "Search district or division",
        "map.list.divisions": "By division · season cases",
        "map.list.districts": "All 64 districts · season cases",
        "map.list.footer": "Risk is 14-day reported cases per 100,000 residents: under 5 low, 5–20 moderate, 20–60 high, above 60 severe.",
        "map.bubble.a11y": "%@, %@ cases, %@ risk",
        "map.you.inDistrict": "You are in %@",
        "map.you.enable": "Show my location",
        "map.you.denied": "Location is off. Turn it on for DengueWatch in Settings to see where you are on the map.",
        "map.you.locating": "Finding your location…",
        "map.you.wholeCountry": "Show the whole country",
        "map.you.outside": "You are outside the area this map covers.",

        "district.division": "%@ division",
        "district.population": "About %@ residents",
        "district.setHome": "Set as my district",
        "district.isHome": "This is your home district",
        "district.stat.season": "Season cases",
        "district.stat.last7": "Last 7 days",
        "district.stat.rate": "14-day rate",
        "district.stat.deaths": "Season deaths",
        "district.rank": "#%@ of 64 districts",
        "district.riskBand": "%@ risk band",
        "district.share": "%@%% of national cases",
        "district.chart.title": "Cases in %@",
        "district.chart.subtitle": "Daily reports with a 7-day average",
        "district.peers.title": "Rest of %@ division",
        "district.peers.subtitle": "Season cases in neighbouring districts",
        "district.picker.title": "My district",
        "district.picker.search": "Search districts",
    ]

    static let bnMap: [String: String] = [
        "map.title": "কোথায় ছড়াচ্ছে",
        "map.metric.total": "মোট রোগী",
        "map.metric.rate": "প্রতি লাখে",
        "map.explain.total": "বৃত্তের আকার মৌসুমের মোট রোগী। বড় শহর এগিয়ে থাকে শুধু বেশি মানুষ থাকার কারণে।",
        "map.explain.rate": "বৃত্তের আকার ১৪ দিনে প্রতি লাখ বাসিন্দায় রোগীর সংখ্যা, যা বড় শহর ও ছোট জেলার মধ্যে তুলনাযোগ্য।",
        "map.legend.risk": "১৪ দিনের ঝুঁকি",
        "map.showList": "তালিকা দেখুন",
        "map.showMap": "মানচিত্র দেখুন",
        "map.search": "জেলা বা বিভাগ খুঁজুন",
        "map.list.divisions": "বিভাগ অনুযায়ী · মৌসুমের রোগী",
        "map.list.districts": "৬৪ জেলা · মৌসুমের রোগী",
        "map.list.footer": "ঝুঁকি হিসাব করা হয় ১৪ দিনে প্রতি লাখ বাসিন্দায় শনাক্ত রোগী দিয়ে: ৫-এর কম কম, ৫–২০ মাঝারি, ২০–৬০ বেশি, ৬০-এর বেশি তীব্র।",
        "map.bubble.a11y": "%@, %@ জন আক্রান্ত, ঝুঁকি %@",
        "map.you.inDistrict": "আপনি আছেন %@ জেলায়",
        "map.you.enable": "আমার অবস্থান দেখান",
        "map.you.denied": "অবস্থান বন্ধ আছে। মানচিত্রে নিজের অবস্থান দেখতে সেটিংসে গিয়ে ডেঙ্গুওয়াচের জন্য চালু করুন।",
        "map.you.locating": "আপনার অবস্থান খোঁজা হচ্ছে…",
        "map.you.wholeCountry": "পুরো দেশ দেখুন",
        "map.you.outside": "এই মানচিত্র যে এলাকা দেখায়, আপনি তার বাইরে আছেন।",

        "district.division": "%@ বিভাগ",
        "district.population": "প্রায় %@ জন বাসিন্দা",
        "district.setHome": "আমার জেলা হিসেবে নির্ধারণ করুন",
        "district.isHome": "এটি আপনার নিজের জেলা",
        "district.stat.season": "মৌসুমের রোগী",
        "district.stat.last7": "গত ৭ দিন",
        "district.stat.rate": "১৪ দিনের হার",
        "district.stat.deaths": "মৌসুমের মৃত্যু",
        "district.rank": "৬৪ জেলার মধ্যে %@ নম্বর",
        "district.riskBand": "ঝুঁকি %@",
        "district.share": "জাতীয় রোগীর %@%%",
        "district.chart.title": "%@ জেলার রোগী",
        "district.chart.subtitle": "দৈনিক হিসাব, সঙ্গে ৭ দিনের গড়",
        "district.peers.title": "%@ বিভাগের অন্যান্য জেলা",
        "district.peers.subtitle": "পার্শ্ববর্তী জেলাগুলোতে মৌসুমের রোগী",
        "district.picker.title": "আমার জেলা",
        "district.picker.search": "জেলা খুঁজুন",
    ]
}
