import Foundation

extension Strings {
    static let enCheck: [String: String] = [
        "care.plan.readings": "Some readings you recorded in the last few days are well outside the usual range: %@. Show them to a doctor along with how you feel. This app does not read them for you.",
        "care.plan.recheck": "Check symptoms again",

        "result.temperatureMovedNote": "Recording your temperature? Use Vital signs in My health, where it is charted with your other readings.",

        "status.normal": "In the usual range",
        "status.outside": "Outside the usual range",
        "status.farOutside": "Well outside the usual range",

        "lab.scan": "Scan a report",
        "lab.scan.note": "The camera reads the values on this phone and fills them in below. Check every number against your report before saving — the camera can misread.",
        "lab.scan.nothing": "Nothing could be read from that scan. Type the values instead.",

        "trend.rising": "Rising",
        "trend.falling": "Falling",
        "trend.steady": "Little change",
        "trend.notEnoughData": "Not enough readings",
        "trend.chart.temperature": "Your temperature",
        "trend.chart.platelets": "Your platelet count",
        "trend.readings": "%@ readings",
        "trend.note": "This shows which way your own readings have moved. It does not say what that means — take the pattern to your doctor.",


        // Lab reports
        "lab.section": "Lab reports",
        "lab.none": "No reports yet.",
        "lab.add": "Add a report",
        "lab.save": "Save report",
        "lab.platelets": "Platelets",
        "lab.haematocrit": "Haematocrit",
        "lab.whiteCells": "White cells",
        "lab.haemoglobin": "Haemoglobin",
        "lab.unit.platelets": "×10³/µL",
        "lab.unit.haematocrit": "%",
        "lab.unit.whiteCells": "×10³/µL",
        "lab.unit.haemoglobin": "g/dL",
        "lab.typicalRange": "Typical %@–%@",
        "lab.outsideTypical": "Outside the typical range",
        "lab.rangeNote": "Typical ranges differ by sex, age and laboratory. Compare these with the reference range printed on your own report, and take the report to your doctor.",
        "lab.flag.low": "Low",
        "lab.flag.high": "High",
        "lab.flag.ok": "Normal",
        "lab.counts": "Blood count",
        "lab.serology": "Dengue tests",
        "lab.test.ns1": "NS1 antigen",
        "lab.test.igm": "IgM antibody",
        "lab.test.igg": "IgG antibody",
        "lab.result.notDone": "Not done",
        "lab.result.negative": "Negative",
        "lab.result.positive": "Positive",
        "lab.timing.ns1": "Usually informative in the first five days of fever.",
        "lab.timing.igm": "Usually detectable from about day five of fever.",
        "lab.timing.igg": "Rises later, and may reflect a past infection.",
        "lab.timingNote": "These describe when each test is usually informative. What a result means for you is a question for your doctor.",
        "lab.reportDate": "Report date",
        "lab.reported": "Reported %@",

        "health.today.title": "Today",
        "health.today.subtitle": "Keeping a daily record makes a pattern visible.",
        "health.today.symptoms": "Record today's symptoms",
        "health.today.vitals": "Record today's vital signs",
        "health.today.done": "Done",
        "health.today.todo": "Not yet",
        "health.latest.title": "Latest assessment",

        // Vital signs
        "vital.temperature": "Temperature",
        "vital.pulse": "Pulse",
        "vital.systolic": "Systolic",
        "vital.diastolic": "Diastolic",
        "vital.oxygenSaturation": "Oxygen saturation",
        "vital.unit.temperature": "",
        "vital.unit.pulse": "bpm",
        "vital.unit.systolic": "mmHg",
        "vital.unit.diastolic": "mmHg",
        "vital.unit.oxygenSaturation": "%",
        "vital.bloodPressure": "Blood pressure",
        "vital.section": "Vital signs",
        "trend.threshold.fever": "fever",
        "vital.record": "Record readings",
        "vital.save": "Save readings",
        "vital.none": "No readings yet.",
        "vital.outsideUsual": "Outside the usual range",
        "vital.outsideUsual.detail": "This app does not interpret readings. Show them to a doctor or pharmacist, especially with a fever.",
        "vital.usualRange": "Usual %@–%@",
        "vital.lastTaken": "Last taken %@",

        // Temperature units
        "temp.unit.label": "Unit",
        "temp.unit.celsius": "Celsius",
        "temp.unit.fahrenheit": "Fahrenheit",
        "temp.outOfRange": "That does not look like a body temperature in %@.",

        // Stepped symptom check
        "step.fever.title": "Do you have a fever?",
        "step.fever.subtitle": "A sudden high fever is usually how dengue starts.",
        "step.fever.yes": "Yes, I have a fever",
        "step.fever.no": "No fever",
        "step.symptoms.title": "What else are you feeling?",
        "step.symptoms.subtitle": "Tick everything from the last 24 hours.",
        "step.warning.title": "Any of these warning signs?",
        "step.warning.subtitle": "These change what you should do. Read them carefully.",
        "step.warning.none": "None of these",
        "step.timeline.title": "Which day of fever?",
        "step.timeline.subtitle": "Counting the first day of fever as day 1.",
        "step.timeline.unknown": "I am not sure",
        "step.risk.title": "Anything that raises your risk?",
        "step.risk.subtitle": "Dengue can be more serious for some people.",
        "step.next": "Continue",
        "step.back": "Back",
        "step.seeResult": "See what to do",
        "step.progress": "Step %@ of %@",
        "step.skip": "Skip",

        // Fever timeline
        "phase.title": "Where you are in the fever",
        "phase.subtitle": "Typical course. Days are counted from the first day of fever.",
        "phase.febrile.name": "Febrile",
        "phase.critical.name": "Critical",
        "phase.recovery.name": "Recovery",
        "phase.critical.note": "This is the window when warning signs most often appear, usually as the fever starts to fall. Feeling better is not by itself a sign that the danger has passed.",
        "phase.a11y.day": "Day %@ of fever, %@ phase.",
        "phase.a11y.unknown": "Fever timeline. No start date given.",

        "check.title": "Symptom check",
        "check.intro": "Tick everything you have felt in the last 24 hours. This is a guide based on WHO dengue criteria, not a diagnosis.",
        "check.seeResult": "See what to do",
        "check.clearAll": "Clear all",

        "symptom.group.core": "Core symptoms",
        "symptom.group.warning": "Dengue warning signs",
        "symptom.group.severe": "Emergency signs",
        "symptom.group.core.footnote": "The usual picture of dengue fever.",
        "symptom.group.warning.footnote": "WHO warning signs. They usually appear as the fever drops, days 3–7.",
        "symptom.group.severe.footnote": "Signs of severe dengue. These need a hospital now.",

        "symptom.fever.title": "Fever above 38°C (100.4°F)",
        "symptom.fever.detail": "Sudden high fever is usually the first sign.",
        "symptom.headache.title": "Severe headache or pain behind the eyes",
        "symptom.headache.detail": "A classic dengue pattern.",
        "symptom.aches.title": "Muscle, joint or bone pain",
        "symptom.aches.detail": "The reason dengue is called breakbone fever.",
        "symptom.rash.title": "Skin rash",
        "symptom.rash.detail": "Often appears 2–5 days after the fever starts.",
        "symptom.nausea.title": "Nausea or loss of appetite",
        "symptom.nausea.detail": "Common in the first days.",
        "symptom.abdominal.title": "Severe or persistent stomach pain",
        "symptom.abdominal.detail": "Tenderness in the belly, not settling.",
        "symptom.vomiting.title": "Vomiting three or more times a day",
        "symptom.vomiting.detail": "Persistent vomiting, or unable to keep fluids down.",
        "symptom.bleeding.title": "Bleeding gums or nose",
        "symptom.bleeding.detail": "Any bleeding from gums, nose or in vomit or stool.",
        "symptom.fatigue.title": "Sudden weakness, restlessness or irritability",
        "symptom.fatigue.detail": "A marked change in how you feel or behave.",
        "symptom.fluid.title": "Swelling of the belly or breathlessness",
        "symptom.fluid.detail": "Fluid build-up in the abdomen or chest.",
        "symptom.noUrine.title": "Little or no urine for 6+ hours",
        "symptom.noUrine.detail": "A sign of dehydration or falling blood pressure.",
        "symptom.faint.title": "Fainting, cold clammy skin, or a racing pulse",
        "symptom.faint.detail": "Possible dengue shock.",
        "symptom.confusion.title": "Confusion, drowsiness or seizures",
        "symptom.confusion.detail": "Altered consciousness.",
        "symptom.heavyBleed.title": "Heavy bleeding",
        "symptom.heavyBleed.detail": "Vomiting blood, black stools, or heavy vaginal bleeding.",

        "check.fever.section": "Your fever",
        "check.fever.knowDate": "I know when the fever started",
        "check.fever.started": "Fever started",
        "check.phase.febrile": "Day %@ of fever — febrile phase. An NS1 test works best now.",
        "check.phase.critical": "Day %@ of fever — the critical phase. Warning signs usually appear as the fever falls, so check yourself twice a day.",
        "check.phase.recovery": "Day %@ of fever — recovery phase for most people, but watch for fluid overload and lingering fatigue.",

        "check.risk.section": "Anything that raises your risk",
        "check.risk.pregnant": "Pregnant",
        "check.risk.age": "Under 5 or over 60 years old",
        "check.risk.chronic": "Diabetes, heart, kidney or liver condition",
        "check.risk.previous": "I have had dengue before",
        "check.risk.footer": "A second dengue infection with a different serotype carries a higher risk of severe disease, which is why previous dengue counts here.",

        "outcome.selfCare.headline": "Low concern right now",
        "outcome.testAdvised.headline": "Get a dengue test",
        "outcome.seeDoctor.headline": "See a doctor today",
        "outcome.emergency.headline": "Go to a hospital now",
        "outcome.selfCare.summary": "Nothing you reported points to dengue. Keep watching for fever, and check again if one starts.",
        "outcome.testAdvised.summary": "Your symptoms fit early dengue. A NS1 antigen test on day 1–5 of fever, or an IgM/IgG test after day 5, will confirm it.",
        "outcome.seeDoctor.summary": "You reported a warning sign. Warning signs mean the illness can worsen quickly and you should be assessed today, not tomorrow.",
        "outcome.emergency.summary": "You reported a sign of severe dengue. This is a medical emergency — go to the nearest hospital emergency department now.",

        "outcome.selfCare.action1": "Drink fluids and rest.",
        "outcome.selfCare.action2": "Use a mosquito net or repellent during the day, when Aedes bites.",
        "outcome.selfCare.action3": "Start this check again on the first day of any fever.",
        "outcome.testAdvised.action1": "Take paracetamol for fever. Do not take aspirin, ibuprofen or other NSAIDs — they raise bleeding risk in dengue.",
        "outcome.testAdvised.action2": "Drink oral rehydration solution, coconut water or plain water steadily through the day.",
        "outcome.testAdvised.action3": "Ask for an NS1 test if the fever started within the last 5 days.",
        "outcome.testAdvised.action4": "Watch for warning signs and re-run this check daily.",
        "outcome.seeDoctor.action1": "See a doctor or go to a hospital today for assessment and a platelet/haematocrit check.",
        "outcome.seeDoctor.action2": "Keep taking fluids on the way. No aspirin or ibuprofen.",
        "outcome.seeDoctor.action3": "Have someone stay with you — warning signs can progress within hours.",
        "outcome.seeDoctor.action4": "Bring a note of when the fever started.",
        "outcome.emergency.action1": "Go to the nearest emergency department immediately, or call 999.",
        "outcome.emergency.action2": "Do not drive yourself.",
        "outcome.emergency.action3": "Tell the triage nurse it may be severe dengue and when the fever started.",

        "result.title": "Your result",
        "result.whatToDo": "What to do now",
        "result.call999": "Call 999",
        "result.findHospital": "Find the nearest hospital",
        "result.addToLog": "Add this to your log",
        "result.keptOnPhone": "Kept on this phone only",
        "result.temperature": "Temperature, optional",
        "result.note": "Note, optional",
        "result.saveEntry": "Save entry",
        "result.disclaimer": "DengueWatch cannot diagnose dengue. Only a clinician and a blood test can. If you feel worse at any point, go to a hospital regardless of what this screen says.",

        "log.title": "My log",
        "log.empty.title": "No entries yet",
        "log.empty.detail": "Run a symptom check, record your vital signs or add a lab report, and they appear here day by day. Having the course of an illness written down is genuinely useful to a doctor.",
        "log.temperature": "Your temperature",
        "log.export": "Export as PDF",
        "log.defaultName": "Log %@",
        "log.rename": "Rename",
        "log.rename.placeholder": "Name this record",
        "log.rename.detail": "Give this record a name you will recognise. Leave it empty to go back to its number.",
        "log.sort": "Order",
        "log.sort.newest": "Newest first",
        "log.sort.oldest": "Oldest first",
        "log.delete.selected": "Delete %@",
        "log.delete.day": "Delete this day",
        "log.pdf.title": "Health log",
        "log.pdf.generated": "Exported %@",
        "log.pdf.symptoms": "S",
        "log.pdf.vitals": "V",
        "log.pdf.labs": "L",
        "log.pdf.noSymptoms": "No symptoms recorded",
        "log.pdf.disclaimer": "This is a personal record kept by the reader, not a medical record and not a diagnosis. S marks a symptom check, V a set of vital-sign readings, L a lab report as the reader entered it.",
        "log.privacyFooter": "This log never leaves your phone. It is not sent to DGHS or to anyone else.",
        "log.confirmDelete": "Delete every entry?",
    ]

    static let bnCheck: [String: String] = [
        "care.plan.readings": "গত কয়েক দিনে লেখা কিছু পরিমাপ স্বাভাবিক সীমার অনেক বাইরে: %@। আপনার শারীরিক অবস্থার সঙ্গে এগুলোও চিকিৎসককে দেখান। এই অ্যাপ আপনার হয়ে এগুলো ব্যাখ্যা করে না।",
        "care.plan.recheck": "আবার উপসর্গ পরীক্ষা করুন",

        "result.temperatureMovedNote": "তাপমাত্রা লিখতে চান? আমার স্বাস্থ্য-এর জীবনচিহ্ন ব্যবহার করুন, সেখানে অন্য পরিমাপের সঙ্গে এটি গ্রাফে দেখা যায়।",

        "status.normal": "স্বাভাবিক সীমার মধ্যে",
        "status.outside": "স্বাভাবিক সীমার বাইরে",
        "status.farOutside": "স্বাভাবিক সীমার অনেক বাইরে",

        "lab.scan": "রিপোর্ট স্ক্যান করুন",
        "lab.scan.note": "ক্যামেরা এই ফোনেই রিপোর্ট পড়ে নিচে বসিয়ে দেয়। সংরক্ষণের আগে প্রতিটি সংখ্যা নিজের রিপোর্টের সঙ্গে মিলিয়ে নিন — ক্যামেরা ভুল পড়তে পারে।",
        "lab.scan.nothing": "স্ক্যান থেকে কিছু পড়া যায়নি। হাতে লিখুন।",

        "trend.rising": "বাড়ছে",
        "trend.falling": "কমছে",
        "trend.steady": "তেমন বদলায়নি",
        "trend.notEnoughData": "যথেষ্ট পরিমাপ নেই",
        "trend.chart.temperature": "আপনার তাপমাত্রা",
        "trend.chart.platelets": "আপনার প্লেটলেট",
        "trend.readings": "%@টি পরিমাপ",
        "trend.note": "এটি শুধু দেখায় আপনার পরিমাপ কোন দিকে যাচ্ছে। এর মানে কী তা বলে না — ধরনটি চিকিৎসককে দেখান।",


        // ল্যাব রিপোর্ট
        "lab.section": "ল্যাব রিপোর্ট",
        "lab.none": "এখনো কোনো রিপোর্ট নেই।",
        "lab.add": "রিপোর্ট যোগ করুন",
        "lab.save": "রিপোর্ট সংরক্ষণ করুন",
        "lab.platelets": "প্লেটলেট",
        "lab.haematocrit": "হেমাটোক্রিট",
        "lab.whiteCells": "শ্বেত রক্তকণিকা",
        "lab.haemoglobin": "হিমোগ্লোবিন",
        "lab.unit.platelets": "×১০³/µL",
        "lab.unit.haematocrit": "%",
        "lab.unit.whiteCells": "×১০³/µL",
        "lab.unit.haemoglobin": "g/dL",
        "lab.typicalRange": "সাধারণত %@–%@",
        "lab.outsideTypical": "সাধারণ সীমার বাইরে",
        "lab.rangeNote": "সাধারণ সীমা লিঙ্গ, বয়স ও ল্যাব অনুযায়ী আলাদা হয়। নিজের রিপোর্টে ছাপা সীমার সঙ্গে মিলিয়ে দেখুন এবং রিপোর্টটি চিকিৎসককে দেখান।",
        "lab.flag.low": "কম",
        "lab.flag.high": "বেশি",
        "lab.flag.ok": "স্বাভাবিক",
        "lab.counts": "রক্তের হিসাব",
        "lab.serology": "ডেঙ্গু পরীক্ষা",
        "lab.test.ns1": "এনএস১ অ্যান্টিজেন",
        "lab.test.igm": "আইজিএম অ্যান্টিবডি",
        "lab.test.igg": "আইজিজি অ্যান্টিবডি",
        "lab.result.notDone": "করা হয়নি",
        "lab.result.negative": "নেগেটিভ",
        "lab.result.positive": "পজিটিভ",
        "lab.timing.ns1": "সাধারণত জ্বরের প্রথম পাঁচ দিনে কার্যকর।",
        "lab.timing.igm": "সাধারণত জ্বরের পঞ্চম দিনের পর থেকে ধরা পড়ে।",
        "lab.timing.igg": "পরে বাড়ে, এবং আগের সংক্রমণও বোঝাতে পারে।",
        "lab.timingNote": "এগুলো বলে কোন পরীক্ষা কখন কার্যকর। আপনার ফল কী বোঝায় তা চিকিৎসকের প্রশ্ন।",
        "lab.reportDate": "রিপোর্টের তারিখ",
        "lab.reported": "%@ রিপোর্ট",

        "health.today.title": "আজ",
        "health.today.subtitle": "প্রতিদিন লিখে রাখলে ধরনটা বোঝা যায়।",
        "health.today.symptoms": "আজকের উপসর্গ লিখুন",
        "health.today.vitals": "আজকের জীবনচিহ্ন লিখুন",
        "health.today.done": "হয়েছে",
        "health.today.todo": "এখনো হয়নি",
        "health.latest.title": "সর্বশেষ মূল্যায়ন",

        // জীবনচিহ্ন
        "vital.temperature": "তাপমাত্রা",
        "vital.pulse": "নাড়ির গতি",
        "vital.systolic": "সিস্টোলিক",
        "vital.diastolic": "ডায়াস্টোলিক",
        "vital.oxygenSaturation": "অক্সিজেনের মাত্রা",
        "vital.unit.temperature": "",
        "vital.unit.pulse": "বিপিএম",
        "vital.unit.systolic": "মিমিএইচজি",
        "vital.unit.diastolic": "মিমিএইচজি",
        "vital.unit.oxygenSaturation": "%",
        "vital.bloodPressure": "রক্তচাপ",
        "vital.section": "জীবনচিহ্ন",
        "trend.threshold.fever": "জ্বর",
        "vital.record": "পরিমাপ লিখুন",
        "vital.save": "সংরক্ষণ করুন",
        "vital.none": "এখনো কোনো পরিমাপ নেই।",
        "vital.outsideUsual": "স্বাভাবিক সীমার বাইরে",
        "vital.outsideUsual.detail": "এই অ্যাপ পরিমাপের ব্যাখ্যা দেয় না। বিশেষত জ্বর থাকলে এগুলো চিকিৎসক বা ফার্মাসিস্টকে দেখান।",
        "vital.usualRange": "স্বাভাবিক %@–%@",
        "vital.lastTaken": "সর্বশেষ %@",

        // তাপমাত্রার একক
        "temp.unit.label": "একক",
        "temp.unit.celsius": "সেলসিয়াস",
        "temp.unit.fahrenheit": "ফারেনহাইট",
        "temp.outOfRange": "%@-এ এটি শরীরের তাপমাত্রা বলে মনে হচ্ছে না।",

        // ধাপে ধাপে উপসর্গ পরীক্ষা
        "step.fever.title": "আপনার কি জ্বর আছে?",
        "step.fever.subtitle": "হঠাৎ তীব্র জ্বর দিয়েই সাধারণত ডেঙ্গু শুরু হয়।",
        "step.fever.yes": "হ্যাঁ, জ্বর আছে",
        "step.fever.no": "জ্বর নেই",
        "step.symptoms.title": "আর কী কী অনুভব করছেন?",
        "step.symptoms.subtitle": "গত ২৪ ঘণ্টার সবকিছু চিহ্নিত করুন।",
        "step.warning.title": "এই বিপদচিহ্নগুলোর কোনোটি আছে?",
        "step.warning.subtitle": "এগুলো থাকলে করণীয় বদলে যায়। মনোযোগ দিয়ে পড়ুন।",
        "step.warning.none": "কোনোটিই নেই",
        "step.timeline.title": "জ্বরের কত দিন?",
        "step.timeline.subtitle": "জ্বরের প্রথম দিনকে ১ম দিন ধরে।",
        "step.timeline.unknown": "আমি নিশ্চিত নই",
        "step.risk.title": "ঝুঁকি বাড়ায় এমন কিছু আছে?",
        "step.risk.subtitle": "কিছু মানুষের জন্য ডেঙ্গু বেশি মারাত্মক হতে পারে।",
        "step.next": "পরবর্তী",
        "step.back": "পেছনে",
        "step.seeResult": "করণীয় দেখুন",
        "step.progress": "ধাপ %@ / %@",
        "step.skip": "এড়িয়ে যান",

        // জ্বরের সময়রেখা
        "phase.title": "আপনি জ্বরের কোন পর্যায়ে",
        "phase.subtitle": "সাধারণ গতিপথ। জ্বরের প্রথম দিন থেকে দিন গোনা হয়।",
        "phase.febrile.name": "জ্বরের পর্যায়",
        "phase.critical.name": "সংকটকাল",
        "phase.recovery.name": "সুস্থ হওয়া",
        "phase.critical.note": "এই সময়েই সবচেয়ে বেশি বিপদচিহ্ন দেখা দেয়, সাধারণত জ্বর কমতে শুরু করার সময়। ভালো লাগা মানেই বিপদ কেটে গেছে তা নয়।",
        "phase.a11y.day": "জ্বরের %@ দিন, %@।",
        "phase.a11y.unknown": "জ্বরের সময়রেখা। শুরুর তারিখ দেওয়া হয়নি।",

        "check.title": "উপসর্গ পরীক্ষা",
        "check.intro": "গত ২৪ ঘণ্টায় আপনার যা যা হয়েছে সব চিহ্নিত করুন। এটি বিশ্ব স্বাস্থ্য সংস্থার নির্দেশনার ভিত্তিতে একটি দিকনির্দেশ, রোগনির্ণয় নয়।",
        "check.seeResult": "কী করণীয় দেখুন",
        "check.clearAll": "সব মুছুন",

        "symptom.group.core": "প্রধান উপসর্গ",
        "symptom.group.warning": "ডেঙ্গুর বিপদচিহ্ন",
        "symptom.group.severe": "জরুরি বিপদচিহ্ন",
        "symptom.group.core.footnote": "ডেঙ্গু জ্বরের সাধারণ চিত্র।",
        "symptom.group.warning.footnote": "বিশ্ব স্বাস্থ্য সংস্থার বিপদচিহ্ন। সাধারণত জ্বর কমার সময়, ৩ থেকে ৭ দিনের মধ্যে দেখা দেয়।",
        "symptom.group.severe.footnote": "মারাত্মক ডেঙ্গুর লক্ষণ। এখনই হাসপাতালে যেতে হবে।",

        "symptom.fever.title": "৩৮°সে (১০০.৪°ফা) এর বেশি জ্বর",
        "symptom.fever.detail": "হঠাৎ তীব্র জ্বরই সাধারণত প্রথম লক্ষণ।",
        "symptom.headache.title": "তীব্র মাথাব্যথা বা চোখের পেছনে ব্যথা",
        "symptom.headache.detail": "ডেঙ্গুর একটি চিরচেনা লক্ষণ।",
        "symptom.aches.title": "মাংসপেশি, গিঁট বা হাড়ে ব্যথা",
        "symptom.aches.detail": "এ কারণেই ডেঙ্গুকে হাড়ভাঙা জ্বর বলা হয়।",
        "symptom.rash.title": "শরীরে র‍্যাশ বা ফুসকুড়ি",
        "symptom.rash.detail": "সাধারণত জ্বর শুরুর ২–৫ দিন পর দেখা দেয়।",
        "symptom.nausea.title": "বমি বমি ভাব বা খাওয়ার রুচি না থাকা",
        "symptom.nausea.detail": "প্রথম কয়েক দিনে সাধারণ।",
        "symptom.abdominal.title": "তীব্র বা একটানা পেটব্যথা",
        "symptom.abdominal.detail": "পেটে ব্যথা যা কমছে না।",
        "symptom.vomiting.title": "দিনে তিনবার বা তার বেশি বমি",
        "symptom.vomiting.detail": "একটানা বমি, বা কিছু খেতে না পারা।",
        "symptom.bleeding.title": "দাঁতের মাড়ি বা নাক দিয়ে রক্ত",
        "symptom.bleeding.detail": "মাড়ি, নাক, বমি বা পায়খানার সঙ্গে যেকোনো রক্তক্ষরণ।",
        "symptom.fatigue.title": "হঠাৎ দুর্বলতা, অস্থিরতা বা খিটখিটে ভাব",
        "symptom.fatigue.detail": "আচরণ বা অনুভূতিতে স্পষ্ট পরিবর্তন।",
        "symptom.fluid.title": "পেট ফুলে যাওয়া বা শ্বাসকষ্ট",
        "symptom.fluid.detail": "পেটে বা বুকে পানি জমা।",
        "symptom.noUrine.title": "৬ ঘণ্টার বেশি সময় প্রস্রাব কম বা না হওয়া",
        "symptom.noUrine.detail": "পানিশূন্যতা বা রক্তচাপ কমে যাওয়ার লক্ষণ।",
        "symptom.faint.title": "অজ্ঞান হওয়া, ঠান্ডা ঘামে ভেজা ত্বক বা দ্রুত নাড়ি",
        "symptom.faint.detail": "ডেঙ্গু শকের আশঙ্কা।",
        "symptom.confusion.title": "বিভ্রান্তি, ঝিমুনি বা খিঁচুনি",
        "symptom.confusion.detail": "জ্ঞানের পরিবর্তন।",
        "symptom.heavyBleed.title": "প্রচণ্ড রক্তক্ষরণ",
        "symptom.heavyBleed.detail": "রক্তবমি, কালো পায়খানা বা অতিরিক্ত যোনিপথে রক্তক্ষরণ।",

        "check.fever.section": "আপনার জ্বর",
        "check.fever.knowDate": "জ্বর কবে শুরু হয়েছে আমি জানি",
        "check.fever.started": "জ্বর শুরু হয়েছে",
        "check.phase.febrile": "জ্বরের %@ দিন — জ্বরের পর্যায়। এখনই এনএস১ পরীক্ষা সবচেয়ে কার্যকর।",
        "check.phase.critical": "জ্বরের %@ দিন — সংকটকালীন পর্যায়। জ্বর কমার সময়ই বিপদচিহ্ন দেখা দেয়, তাই দিনে দুবার নিজেকে পরীক্ষা করুন।",
        "check.phase.recovery": "জ্বরের %@ দিন — বেশিরভাগ মানুষের সুস্থ হওয়ার পর্যায়, তবে শরীরে পানি জমা ও দীর্ঘস্থায়ী দুর্বলতার দিকে খেয়াল রাখুন।",

        "check.risk.section": "যেসব কারণে ঝুঁকি বাড়ে",
        "check.risk.pregnant": "গর্ভবতী",
        "check.risk.age": "৫ বছরের কম বা ৬০ বছরের বেশি বয়স",
        "check.risk.chronic": "ডায়াবেটিস, হৃদরোগ, কিডনি বা লিভারের সমস্যা",
        "check.risk.previous": "আগে ডেঙ্গু হয়েছিল",
        "check.risk.footer": "ভিন্ন ধরনের ভাইরাসে দ্বিতীয়বার ডেঙ্গু হলে মারাত্মক হওয়ার ঝুঁকি বেশি থাকে, তাই আগের ডেঙ্গুর তথ্য এখানে গুরুত্বপূর্ণ।",

        "outcome.selfCare.headline": "এখনই দুশ্চিন্তার কিছু নেই",
        "outcome.testAdvised.headline": "ডেঙ্গু পরীক্ষা করান",
        "outcome.seeDoctor.headline": "আজই ডাক্তার দেখান",
        "outcome.emergency.headline": "এখনই হাসপাতালে যান",
        "outcome.selfCare.summary": "আপনি যা জানিয়েছেন তাতে ডেঙ্গুর ইঙ্গিত নেই। জ্বরের দিকে খেয়াল রাখুন, জ্বর এলে আবার পরীক্ষা করুন।",
        "outcome.testAdvised.summary": "আপনার উপসর্গ প্রাথমিক ডেঙ্গুর সঙ্গে মেলে। জ্বরের ১–৫ দিনে এনএস১ অ্যান্টিজেন পরীক্ষা, অথবা ৫ দিনের পর আইজিএম/আইজিজি পরীক্ষা করলে নিশ্চিত হওয়া যাবে।",
        "outcome.seeDoctor.summary": "আপনি একটি বিপদচিহ্ন জানিয়েছেন। বিপদচিহ্ন মানে অবস্থা দ্রুত খারাপ হতে পারে, তাই আগামীকাল নয় — আজই পরীক্ষা করানো দরকার।",
        "outcome.emergency.summary": "আপনি মারাত্মক ডেঙ্গুর লক্ষণ জানিয়েছেন। এটি জরুরি অবস্থা — এখনই নিকটতম হাসপাতালের জরুরি বিভাগে যান।",

        "outcome.selfCare.action1": "পর্যাপ্ত পানি পান করুন এবং বিশ্রাম নিন।",
        "outcome.selfCare.action2": "দিনের বেলায় মশারি বা মশা প্রতিরোধক ব্যবহার করুন, কারণ এডিস দিনেই কামড়ায়।",
        "outcome.selfCare.action3": "জ্বর এলে প্রথম দিনেই আবার এই পরীক্ষা করুন।",
        "outcome.testAdvised.action1": "জ্বরের জন্য শুধু প্যারাসিটামল খান। অ্যাসপিরিন, আইবুপ্রোফেন বা অন্য এনএসএআইডি খাবেন না — ডেঙ্গুতে এগুলো রক্তক্ষরণের ঝুঁকি বাড়ায়।",
        "outcome.testAdvised.action2": "সারা দিন ধরে খাবার স্যালাইন, ডাবের পানি বা বিশুদ্ধ পানি পান করুন।",
        "outcome.testAdvised.action3": "গত ৫ দিনের মধ্যে জ্বর শুরু হলে এনএস১ পরীক্ষা করাতে বলুন।",
        "outcome.testAdvised.action4": "বিপদচিহ্নের দিকে খেয়াল রাখুন এবং প্রতিদিন এই পরীক্ষা আবার করুন।",
        "outcome.seeDoctor.action1": "আজই ডাক্তার দেখান বা হাসপাতালে যান এবং প্লাটিলেট ও হেমাটোক্রিট পরীক্ষা করান।",
        "outcome.seeDoctor.action2": "যাওয়ার পথেও পানি পান করতে থাকুন। অ্যাসপিরিন বা আইবুপ্রোফেন নয়।",
        "outcome.seeDoctor.action3": "কাউকে সঙ্গে রাখুন — বিপদচিহ্ন কয়েক ঘণ্টার মধ্যেই খারাপ হতে পারে।",
        "outcome.seeDoctor.action4": "জ্বর কবে শুরু হয়েছে তা লিখে সঙ্গে নিন।",
        "outcome.emergency.action1": "এখনই নিকটতম জরুরি বিভাগে যান, অথবা ৯৯৯-এ ফোন করুন।",
        "outcome.emergency.action2": "নিজে গাড়ি চালাবেন না।",
        "outcome.emergency.action3": "জরুরি বিভাগে জানান যে এটি মারাত্মক ডেঙ্গু হতে পারে এবং জ্বর কবে শুরু হয়েছে।",

        "result.title": "আপনার ফলাফল",
        "result.whatToDo": "এখন যা করবেন",
        "result.call999": "৯৯৯-এ ফোন করুন",
        "result.findHospital": "নিকটতম হাসপাতাল খুঁজুন",
        "result.addToLog": "আপনার তালিকায় যোগ করুন",
        "result.keptOnPhone": "শুধু এই ফোনেই থাকবে",
        "result.temperature": "তাপমাত্রা, ঐচ্ছিক",
        "result.note": "মন্তব্য, ঐচ্ছিক",
        "result.saveEntry": "সংরক্ষণ করুন",
        "result.disclaimer": "ডেঙ্গুওয়াচ ডেঙ্গু নির্ণয় করতে পারে না। কেবল একজন চিকিৎসক ও রক্ত পরীক্ষাই তা পারে। যেকোনো সময় অবস্থা খারাপ মনে হলে এই পর্দা যা-ই বলুক, হাসপাতালে যান।",

        "log.title": "আমার তালিকা",
        "log.empty.title": "এখনো কিছু নেই",
        "log.empty.detail": "উপসর্গ পরীক্ষা করুন, জীবনচিহ্ন লিখে রাখুন বা ল্যাব রিপোর্ট যোগ করুন — এখানে দিন ধরে ধরে দেখা যাবে। অসুস্থতার হিসাব লেখা থাকলে ডাক্তারের জন্য তা সত্যিই কাজে লাগে।",
        "log.temperature": "আপনার তাপমাত্রা",
        "log.export": "পিডিএফ তৈরি করুন",
        "log.defaultName": "লগ %@",
        "log.rename": "নাম বদলান",
        "log.rename.placeholder": "এই হিসাবের নাম দিন",
        "log.rename.detail": "চিনতে সুবিধা হয় এমন একটি নাম দিন। খালি রাখলে আবার নম্বর দেখাবে।",
        "log.sort": "ক্রম",
        "log.sort.newest": "নতুন আগে",
        "log.sort.oldest": "পুরোনো আগে",
        "log.delete.selected": "%@টি মুছুন",
        "log.delete.day": "এই দিনের সব মুছুন",
        "log.pdf.title": "স্বাস্থ্য বিবরণী",
        "log.pdf.generated": "%@ তারিখে তৈরি",
        "log.pdf.symptoms": "উ",
        "log.pdf.vitals": "জ",
        "log.pdf.labs": "ল",
        "log.pdf.noSymptoms": "কোনো উপসর্গ লেখা হয়নি",
        "log.pdf.disclaimer": "এটি ব্যবহারকারীর নিজের রাখা হিসাব — কোনো মেডিকেল রেকর্ড বা রোগনির্ণয় নয়। উ মানে উপসর্গ পরীক্ষা, জ মানে জীবনচিহ্নের পরিমাপ, ল মানে ব্যবহারকারীর লেখা ল্যাব রিপোর্ট।",
        "log.privacyFooter": "এই তালিকা কখনো আপনার ফোন থেকে বের হয় না। এটি স্বাস্থ্য অধিদপ্তর বা অন্য কারও কাছে পাঠানো হয় না।",
        "log.confirmDelete": "সব তথ্য মুছে ফেলবেন?",
    ]
}
